### ISSUE TITLE
Please no apt -y in configure

### ISSUE THREAD

**Issue by C138** [jafl/jx_application_framework#2]
It's too dangerous for local environment.

I have to repair unwanted removal of packages ...

At least provide a dry-run mode or something like that to let the user choose if s/he rellay wants to remove those packages 

Thanks.

**Comment by jafl** [comment]
`apt remove` is marked as a hack.  I will investigate to see if it's even needed any longer.

**Comment by jafl** [comment]
`apt remove` is no longer needed, so it has been removed.
